apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blackfire.fullname" . }}
  labels:
    {{- include "blackfire.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blackfire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blackfire.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BLACKFIRE_SERVER_ID
              {{- if .Values.blackfire.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.blackfire.existingSecret }}
                  key: server_id
              {{- else }}
              value: {{ .Values.blackfire.server_id }}
              {{- end }}
            - name: BLACKFIRE_SERVER_TOKEN
              {{- if .Values.blackfire.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.blackfire.existingSecret }}
                  key: server_token
              {{- else }}
              value: {{ .Values.blackfire.server_token }}
              {{- end }}
            - name: BLACKFIRE_LOG_LEVEL
              value: {{ .Values.blackfire.log_level | default 1 | quote }}
          ports:
            - name: agent
              containerPort: 8707
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: agent
          readinessProbe:
            tcpSocket:
              port: agent
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
